[versions]
gradle-android = "8.5.0"

kotlin-core = "2.0.0"
kotlin-coroutines = "1.9.0-RC" # K2
kotlin-immutableCollections = "0.3.7"

androidx-activity = "1.9.0"

compose-material3 = "1.3.0-beta04"
compose-activity = "1.9.0"

okio = "3.9.0"
okhttp = "5.0.0-alpha.14"
moshi-runtime = "1.15.1"
moshi-extensions = "0.27.2"

spotless = "6.25.0"
ktlint = "1.3.1"

test-assertk = "0.28.1"

[plugins]
andriod-application = { id = "com.android.application", version.ref = "gradle-android" }

spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
moshi = { id = "dev.zacsweers.moshix", version.ref = "moshi-extensions" }

[libraries]
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-immutableCollections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutableCollections" }

androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }

compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
moshi-runtime = { module = "com.squareup.moshi:moshi", version.ref = "moshi-runtime" }
moshi-adapter-immutableCollections = { module = "dev.zacsweers.moshix:moshi-immutable-adapters", version.ref = "moshi-extensions" }

test-assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "test-assertk" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }

ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" } # for Renovate
